// =============================================================================
// summarizer.ts - Rolling history summarization module.
//
// Instead of dumping the full chat history every turn, this module maintains
// a "Story So Far" summary that grows over the first N turns, then rolls
// forward: when the summary exceeds a threshold, the oldest summary is merged
// into the latest one and the corresponding history window is discarded.
//
// The summary is generated by the AI itself during a dedicated summarization
// turn, ensuring factual consistency with the narrative voice.
// =============================================================================

import { ChatMessage } from "../state/GameState";
import { StateModule } from "../state/state";

/** Configuration for the summarization system. */
export interface SummarizerConfig {
  /** Max turns before triggering a roll-forward summary. */
  maxHistoryTurns: number;
  /** Max characters for the "Story So Far" summary. */
  maxSummaryChars: number;
  /** Min turns between automatic summaries (avoids spamming). */
  minTurnsBetweenSummaries: number;
}

const DEFAULT_CONFIG: SummarizerConfig = {
  maxHistoryTurns: 16, // Keep ~16 recent turns in full detail
  maxSummaryChars: 2000, // ~500 tokens for the summary
  minTurnsBetweenSummaries: 6, // Summarize roughly every 6 turns
};

/** Internal state tracking summarization progress. */
interface SummarizerState {
  turnCount: number;
  summary: string;
  lastSummaryTurn: number;
  config: SummarizerConfig;
}

let internal: SummarizerState | null = null;

/**
 * Initialize the summarizer. Must be called once at game start.
 */
export function initSummarizer(config?: Partial<SummarizerConfig>): void {
  const cfg = { ...DEFAULT_CONFIG, ...config };
  internal = {
    turnCount: 0,
    summary: "",
    lastSummaryTurn: 0,
    config: cfg,
  };
}

/**
 * Get the current summary text. Empty string if not yet initialized.
 */
export function getSummary(): string {
  return internal?.summary ?? "";
}

/**
 * Called at the beginning of each turn to track progress and decide
 * if a summary roll-forward is needed.
 * Returns the compressed context payload (summary + recent turns).
 */
export function prepareContext(): {
  summary: string;
  recentHistory: ChatMessage[];
  estimatedTokens: number;
} {
  if (!internal) {
    return { summary: "", recentHistory: [], estimatedTokens: 0 };
  }

  const s = StateModule.state;
  internal.turnCount++;

  const allHistory = s.history;
  const recent = allHistory.slice(-internal.config.maxHistoryTurns);

  // Decide if we need to roll forward the summary.
  const turnsSinceLast = internal.turnCount - internal.lastSummaryTurn;
  const shouldSummarize =
    turnsSinceLast >= internal.config.minTurnsBetweenSummaries &&
    recent.length >= internal.config.minTurnsBetweenSummaries;

  if (shouldSummarize) {
    // Trigger a background summarization.
    // The actual AI call happens asynchronously; in the meantime,
    // we return the full recent history until the summary is ready.
    triggerRollForward(allHistory);
  }

  // Return the current best context.
  return {
    summary: internal.summary,
    recentHistory: recent,
    estimatedTokens: recent.reduce(function(acc: number, m: { content: string }) { return acc + m.content.length; }, 0) + internal.summary.length,
  };
}

/**
 * Called after a turn completes to store the AI's raw response for
 * history tracking.
 */
export function recordTurn(_role: "user" | "assistant", _content: string): void {
  // Nothing extra needed - turn.ts handles pushing to state.history.
}

/**
 * Manually set the summary (called after the AI returns a summary).
 */
export function setSummary(newSummary: string): void {
  if (!internal) return;
  internal.summary = newSummary;
  internal.lastSummaryTurn = internal.turnCount;
}

/**
 * Reset the summarizer state (called on new game start).
 */
export function resetSummarizer(): void {
  internal = null;
}

/**
 * Merge the full history into a concise "Story So Far" summary
 * via the AI. This is called asynchronously in the background.
 */
async function triggerRollForward(history: ChatMessage[]): Promise<void> {
  if (!internal) return;

  // Build a prompt for the AI to summarize the story so far.
  const summaryPrompt = `You are a story summarizer. Given the following conversation history from an interactive novel, produce a concise "Story So Far" summary.

RULES:
- Write in third-person narrative style.
- Include key plot points, character developments, and established facts.
- Mention important NPC relationships and their current dispositions.
- Note the MC's current location, time, and inventory highlights.
- Keep it under ${internal.config.maxSummaryChars} characters.
- Do NOT include dialogue verbatim; summarize the essence.
- Do NOT predict future events.

Conversation History:
${history.map((m) => `[${m.role}]: ${m.content.substring(0, 2000)}`).join("\n\n")}

Produce the summary now. Return ONLY the summary text, nothing else.`;

  try {
    const config = StateModule.state.api;
    const delays = [1000, 2000, 4000, 8000, 16000];
    let retries = 0;

    async function doCall(): Promise<string> {
      if (config.provider === "gemini") {
        const apiKey = config.key || "";
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${config.model}:generateContent?key=${apiKey}`;
        const payload = {
          contents: [{ role: "user", parts: [{ text: summaryPrompt }] }],
        };
        const resp = await fetch(url, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
        });
        if (!resp.ok) throw new Error(`Gemini Error ${resp.status}`);
        const data = await resp.json();
        return data.candidates[0].content.parts[0].text;
      }
      if (config.provider === "openai") {
        const url = "https://api.openai.com/v1/chat/completions";
        const resp = await fetch(url, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${config.key}`,
          },
          body: JSON.stringify({
            model: config.model || "gpt-4o",
            messages: [{ role: "user", content: summaryPrompt }],
          }),
        });
        if (!resp.ok) throw new Error(`OpenAI Error ${resp.status}`);
        const data = await resp.json();
        return data.choices[0].message.content;
      }
      // Local
      const url = config.url || "http://localhost:11434/api/chat";
      const resp = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: config.model,
          messages: [{ role: "user", content: summaryPrompt }],
          stream: false,
        }),
      });
      if (!resp.ok) throw new Error(`Local API Error ${resp.status}`);
      const data = await resp.json();
      return data.message.content;
    }

    for (;;) {
      try {
        const result = await doCall();
        // Clean up the summary - strip markdown/code fences.
        const clean = result
          .replace(/```[\s\S]*?```/g, "")
          .replace(/^#\s*Story So Far\s*\n?/i, "")
          .trim();
        if (clean.length > 0) {
          setSummary(clean);
        }
        break;
      } catch (error) {
        if (retries < 5) {
          await new Promise((r) => setTimeout(r, delays[retries]));
          retries++;
        } else {
          console.warn("Summarization failed after retries:", error);
          break;
        }
      }
    }
  } catch {
    // Silently fail - we still have recent history as fallback.
  }
}

/**
 * Get the compressed history payload for API calls.
 * Combines the summary with recent turns.
 */
export function getCompressedHistory(): ChatMessage[] {
  if (!internal) return [];
  const s = StateModule.state;
  const recent = s.history.slice(-internal.config.maxHistoryTurns);

  if (!internal.summary) return recent;

  // Prepend a synthetic summary message.
  return [{ role: "user", content: `[[STORY SUMMARY]]\n${internal.summary}\n\n[[RECENT CONVERSATION]]` }, ...recent];
}
